### ISSUE TITLE
DADA2 + Blastn (Assignment 'Helping others')

### ISSUE THREAD

**Issue by skreling** [fish546-2021/joe-benthos#2]
Was wondering if you got the DADA2 to work on your personal files outside of the mouse tutorial? Also have you tried using blastn yet? It seems a good deal easier to comprehend on how to code it out and also what was happening on the backend (at least for me!). 

I really like your repo organization and read.me make it really easy to find where everything is.

**Comment by jdduprey** [comment]
I have not! I got stuck on the demultiplexing step, and it seems that my lab indexes reads in a certain way to save time and money - but that this requires a custom demultiplexer. I will try blastn, which may be more productive than continuing to flounder with the custom scripts. Thanks for the suggestions Sam!
